@IsTest
private class LeadUtils_Test 
{
    // update this class to unit test the LeadUtils class. 
    // Ensure that you create positive and negative test cases
    // as appropriate, and test with leads owned by multiple users.

    // as the utility class can be called from a trigger it needs to
    // be able to handle up to 200 records without breaking limits

    // Null lead/user Mentz_Key_Field__c values are valid and will
    // match againt Mentz_Lead_User_Key__c records where those values
    // are null - this should also be tested.

    // 100% coverage can be achieved without testing all scenarios,
    // so don't stop just because you have full coverage.
}
